kind: Service
apiVersion: v1
metadata:
  name: career-plan-admin-audit-service
spec:
  selector:
    app: career-plan-admin-audit
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: career-plan-admin-audit-deployment
  labels:
    app: career-plan-admin-audit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: career-plan-admin-audit
  template:
    metadata:
      labels:
        app: career-plan-admin-audit
    spec:
      containers:
      - name: career-plan-admin-audit
        image: docker.io/deepakkhetwal/career-plan-admin-audit-service:latest
        ports:
        - containerPort: 8080